name: deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 部署到 Cloudflare Pages
    permissions:
      deployments: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 部署到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: artab
          directory: website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 